### ISSUE TITLE
Method & class names need work

### ISSUE THREAD

**Issue by misterfifths** [learn-co-curriculum/ios-collections#1]
`FISCollections` is a weird name for what amounts to a collection of helpers. maybe... `FISCollectionUtilities` or something.

`sortArrayAsc:` / `sortArrayDesc:` - they don't do anything to the array argument, so these names are misleading. `arrayBySortingArrayAscending:`. or `sortedArrayAscending:`.

`countWordsInStory:` returns a dictionary?! `countOfWordsInString:` or something? Maybe keeping "story" is ok, but `countWords...` is weird.

`addS:` .. what the hell does that do? The name should make it obvious what the arguments are and what it's going to do.  `arrayByAppendingSToStrings:` or something?

`swapElements:`... again, what is that going to do? Which does it swap? `swapSecondAndThirdObjects:`.

`greaterAndLessThan10:` oof. `splitArrayAt10:` or something? This is a tough one. In the real world I'd probably have it return a 2-element array, or (more likely), use `NSArray **` to return them as out parameters. `bisectArrayAt10:`??

**Comment by markedwardmurray** [comment]
method names rewritten
